//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cat_origen
    {
        public tbl_cat_origen()
        {
            this.tbl_incidencias = new HashSet<tbl_incidencias>();
        }
    
        public int id_origen { get; set; }
        public string cve_origen { get; set; }
        public string nom_origen { get; set; }
    
        public virtual ICollection<tbl_incidencias> tbl_incidencias { get; set; }
    }
}
