//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inc_img
    {
        public int id_img { get; set; }
        public int id_inc { get; set; }
        public string fila_frontal { get; set; }
        public string fila_pallet { get; set; }
        public string acerca_pallet { get; set; }
        public string tarima_dañada { get; set; }
        public string conte_fila { get; set; }
        public string sacos_daña { get; set; }
    
        public virtual tbl_incidencias tbl_incidencias { get; set; }
    }
}
