//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DHL_SCEntities : DbContext
    {
        public DHL_SCEntities()
            : base("name=DHL_SCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cat_familia> tbl_cat_familia { get; set; }
        public virtual DbSet<tbl_cat_incidencia> tbl_cat_incidencia { get; set; }
        public virtual DbSet<tbl_cat_matAfectado> tbl_cat_matAfectado { get; set; }
        public virtual DbSet<tbl_cat_origen> tbl_cat_origen { get; set; }
        public virtual DbSet<tbl_cat_sts> tbl_cat_sts { get; set; }
        public virtual DbSet<tbl_cat_turno> tbl_cat_turno { get; set; }
        public virtual DbSet<tbl_cat_udm> tbl_cat_udm { get; set; }
        public virtual DbSet<tbl_inc_img> tbl_inc_img { get; set; }
        public virtual DbSet<tbl_incidencias> tbl_incidencias { get; set; }
    
        public virtual ObjectResult<sp_cons_incidencias_Result> sp_cons_incidencias(Nullable<int> opc)
        {
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cons_incidencias_Result>("sp_cons_incidencias", opcParameter);
        }
    
        public virtual ObjectResult<sp_Adm_incidencias_Result> sp_Adm_incidencias(Nullable<System.DateTime> fec_registro, string no_STO, string cve_turno, string aut_coord, string cve_incidiencia, string cve_familia, string cve_origen, string codigo, string pO, string factura, string lote, string descripcion, string cve_material, Nullable<double> cantidad, string cve_udm, string norma_estiba, string transporte, string operador, string accion_Contencion, Nullable<System.DateTime> fec_cierre, Nullable<int> atendido, string status, string evidencia, string observacion, string filaFrontal, string filaPallet, string acercaPallet, string tarimaDanada, string sacosDanado, Nullable<int> opc)
        {
            var fec_registroParameter = fec_registro.HasValue ?
                new ObjectParameter("fec_registro", fec_registro) :
                new ObjectParameter("fec_registro", typeof(System.DateTime));
    
            var no_STOParameter = no_STO != null ?
                new ObjectParameter("no_STO", no_STO) :
                new ObjectParameter("no_STO", typeof(string));
    
            var cve_turnoParameter = cve_turno != null ?
                new ObjectParameter("cve_turno", cve_turno) :
                new ObjectParameter("cve_turno", typeof(string));
    
            var aut_coordParameter = aut_coord != null ?
                new ObjectParameter("aut_coord", aut_coord) :
                new ObjectParameter("aut_coord", typeof(string));
    
            var cve_incidienciaParameter = cve_incidiencia != null ?
                new ObjectParameter("cve_incidiencia", cve_incidiencia) :
                new ObjectParameter("cve_incidiencia", typeof(string));
    
            var cve_familiaParameter = cve_familia != null ?
                new ObjectParameter("cve_familia", cve_familia) :
                new ObjectParameter("cve_familia", typeof(string));
    
            var cve_origenParameter = cve_origen != null ?
                new ObjectParameter("cve_origen", cve_origen) :
                new ObjectParameter("cve_origen", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var pOParameter = pO != null ?
                new ObjectParameter("PO", pO) :
                new ObjectParameter("PO", typeof(string));
    
            var facturaParameter = factura != null ?
                new ObjectParameter("factura", factura) :
                new ObjectParameter("factura", typeof(string));
    
            var loteParameter = lote != null ?
                new ObjectParameter("lote", lote) :
                new ObjectParameter("lote", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var cve_materialParameter = cve_material != null ?
                new ObjectParameter("cve_material", cve_material) :
                new ObjectParameter("cve_material", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(double));
    
            var cve_udmParameter = cve_udm != null ?
                new ObjectParameter("cve_udm", cve_udm) :
                new ObjectParameter("cve_udm", typeof(string));
    
            var norma_estibaParameter = norma_estiba != null ?
                new ObjectParameter("norma_estiba", norma_estiba) :
                new ObjectParameter("norma_estiba", typeof(string));
    
            var transporteParameter = transporte != null ?
                new ObjectParameter("transporte", transporte) :
                new ObjectParameter("transporte", typeof(string));
    
            var operadorParameter = operador != null ?
                new ObjectParameter("operador", operador) :
                new ObjectParameter("operador", typeof(string));
    
            var accion_ContencionParameter = accion_Contencion != null ?
                new ObjectParameter("accion_Contencion", accion_Contencion) :
                new ObjectParameter("accion_Contencion", typeof(string));
    
            var fec_cierreParameter = fec_cierre.HasValue ?
                new ObjectParameter("fec_cierre", fec_cierre) :
                new ObjectParameter("fec_cierre", typeof(System.DateTime));
    
            var atendidoParameter = atendido.HasValue ?
                new ObjectParameter("atendido", atendido) :
                new ObjectParameter("atendido", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var evidenciaParameter = evidencia != null ?
                new ObjectParameter("evidencia", evidencia) :
                new ObjectParameter("evidencia", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("observacion", observacion) :
                new ObjectParameter("observacion", typeof(string));
    
            var filaFrontalParameter = filaFrontal != null ?
                new ObjectParameter("filaFrontal", filaFrontal) :
                new ObjectParameter("filaFrontal", typeof(string));
    
            var filaPalletParameter = filaPallet != null ?
                new ObjectParameter("filaPallet", filaPallet) :
                new ObjectParameter("filaPallet", typeof(string));
    
            var acercaPalletParameter = acercaPallet != null ?
                new ObjectParameter("acercaPallet", acercaPallet) :
                new ObjectParameter("acercaPallet", typeof(string));
    
            var tarimaDanadaParameter = tarimaDanada != null ?
                new ObjectParameter("tarimaDanada", tarimaDanada) :
                new ObjectParameter("tarimaDanada", typeof(string));
    
            var sacosDanadoParameter = sacosDanado != null ?
                new ObjectParameter("sacosDanado", sacosDanado) :
                new ObjectParameter("sacosDanado", typeof(string));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Adm_incidencias_Result>("sp_Adm_incidencias", fec_registroParameter, no_STOParameter, cve_turnoParameter, aut_coordParameter, cve_incidienciaParameter, cve_familiaParameter, cve_origenParameter, codigoParameter, pOParameter, facturaParameter, loteParameter, descripcionParameter, cve_materialParameter, cantidadParameter, cve_udmParameter, norma_estibaParameter, transporteParameter, operadorParameter, accion_ContencionParameter, fec_cierreParameter, atendidoParameter, statusParameter, evidenciaParameter, observacionParameter, filaFrontalParameter, filaPalletParameter, acercaPalletParameter, tarimaDanadaParameter, sacosDanadoParameter, opcParameter);
        }
    
        public virtual ObjectResult<sp_cons_img_Result> sp_cons_img(Nullable<int> idInc, Nullable<int> opc)
        {
            var idIncParameter = idInc.HasValue ?
                new ObjectParameter("idInc", idInc) :
                new ObjectParameter("idInc", typeof(int));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cons_img_Result>("sp_cons_img", idIncParameter, opcParameter);
        }
    
        public virtual ObjectResult<sp_adm_opciones_Result> sp_adm_opciones(string nom_opc, Nullable<int> opc, Nullable<int> sub_opc)
        {
            var nom_opcParameter = nom_opc != null ?
                new ObjectParameter("nom_opc", nom_opc) :
                new ObjectParameter("nom_opc", typeof(string));
    
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            var sub_opcParameter = sub_opc.HasValue ?
                new ObjectParameter("sub_opc", sub_opc) :
                new ObjectParameter("sub_opc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_adm_opciones_Result>("sp_adm_opciones", nom_opcParameter, opcParameter, sub_opcParameter);
        }
    
        public virtual ObjectResult<sp_cons_datos_Result> sp_cons_datos(Nullable<int> opc, string cve_filtro, string cve_filtro2)
        {
            var opcParameter = opc.HasValue ?
                new ObjectParameter("opc", opc) :
                new ObjectParameter("opc", typeof(int));
    
            var cve_filtroParameter = cve_filtro != null ?
                new ObjectParameter("cve_filtro", cve_filtro) :
                new ObjectParameter("cve_filtro", typeof(string));
    
            var cve_filtro2Parameter = cve_filtro2 != null ?
                new ObjectParameter("cve_filtro2", cve_filtro2) :
                new ObjectParameter("cve_filtro2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_cons_datos_Result>("sp_cons_datos", opcParameter, cve_filtroParameter, cve_filtro2Parameter);
        }
    }
}
